<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="with=device-width, initial-scale=1.0">
  <title> Intro to Digital Fabrication </title>
  <link rel="stylesheet"href="../style.css">
  <link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400&display=swap" rel="stylesheet">

</head>
<body>
<section class="header">
  <nav>
    <a href="index.html"> </a>
    <div class= "nav-links">
      <ul>
        <li><a href="../index.html">HOME</a></li>
        <li><a href="../about.html">ABOUT ME</a></li>
      </ul>
    </div>
  </nav>

<div class="text-box">
  <h1> Week 3: Electronics and Tools </h1>
</div>
  

</section>

<!---------------------- week 2 Cutting---------->
</section  class= "about us">

<div class="row">
<div class= "about-col">
<h1> Assignment  </h1>
<p>  For this week's assignment we had to create a kinetic structure that was able to be moved through a circuitry. Then, used a multimeter to measure the voltages in the circuit. Use Ohm's Law to calculate current through the circuit. Document your work and learning. Include at least one video/ gif of the sculpture. </p>

<h1> Press-Fit Construction Kit </h1>

<h1> Materials Used </h1>
<p> - Calipers 
- Screwdriver 
- Screw 
- Wood
- Motor 
- Breadboard circuit 
- Fusion 360
- Arduino 
- Potentiometer 
- Hot glue 
 </p>


<h1> Introduction </h1>

<p> Since we had to create a kinetic structure, and is summer meaning warm weather, I decided to use the opportunity to create something useful that I could use and benefit from it. So, decided to go ahead and do a fan. </p>

<h1> Dimensions + Drawings </h1>

<P> I started by drawing a schematic representation with all measures of the parts I wanted to include in my design. </p>

<img src="./gara.png">

<h1> Building Procedure  </h1>

<p>  I started by doing the body in the form of a cylinder, and then continue on to create the holder and eventually the screw. My screw driver was 5.5mmm. Below, I have attached a picture of how it is simmulated.
 </p>


<h1> Final Product </h1>

<p> This is the final result of the pieces assembled. I would definetely say it took me around -5min to print my pieces. The wheels definetely proceeded to come the way that I expected and perfectly fit into each other on the second try! </p>





</div>
<div class="about-col">



</body>
</html>